[package]
name = "gwasm-runner"
version = "0.1.1"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
description = "Command line tool for running gWasm compatible apps locally, via Golem Unlimited or via Brass Golem."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "gwasm-api"
]

[dependencies]
log="0.4"
env_logger = "0.6"
failure="0.1.5"
sp-wasm-engine = { git = "https://github.com/golemfactory/sp-wasm", branch="wasm-runner" }
#sp-wasm-engine = { path="../sp-wasm/sp-wasm-engine" }

structopt = { version="0.2", features = ["wrap_help", "suggestions", "color"] }
app_dirs = "1.2.1"
uuid = { version = "0.7", features = ["serde", "v4"] }
gwasm-api = { path = "gwasm-api" }
gwasm-brass-api = { git = "https://github.com/golemfactory/gwasm-rust-api", branch = "brass-runner", package = "gwasm-api" }
serde_json="1.0.40"
serde= "1.0.101"
