[package]
name = "gwasm-runner"
version = "0.1.1"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
description = "Command line tool for running gWasm compatible apps locally, via Golem Unlimited or via Brass Golem."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "gwasm-api"
]

[features]
default=['with-gu-mode']
with-gu-mode=['zip', 'awc', 'actix', 'gu-client', 'gu-wasm-env-api', 'futures', 'actix-files','tokio-timer']

[dependencies]
log="0.4"
env_logger = "0.6"
failure="0.1"
sp-wasm-engine = { git = "https://github.com/golemfactory/sp-wasm", branch="wasm-runner" }
structopt = { version="0.2", features = ["wrap_help", "suggestions", "color"] }
app_dirs = "1.2.1"
uuid = { version = "0.7", features = ["serde", "v4"] }
gwasm-api = { path = "gwasm-api" }
serde_json="1.0.40"
serde= "1.0.99"
bytes = "0.4"

[dependencies.zip]
version = "0.5.3"
optional=true

[dependencies.awc]
version = "0.2.6"
optional = true

[dependencies.gu-client]
git = "https://github.com/golemfactory/golem-unlimited.git"
branch="feature/api-on-actix-http-1"
#path="/home/prekucki/workspace/gu/golem-unlimited/gu-client"
optional = true

[dependencies.actix-http]
version ="0.2.4"
optional = true

[dependencies.actix-files]
version ="0.1"
optional = true


[dependencies.actix]
version="0.8"
optional=true

[dependencies.gu-wasm-env-api]
git="https://github.com/golemfactory/gu-exec-env-driver-wasm.git"
optional = true


[dependencies.futures]
version = "0.1.29"
optional=true

[dependencies.tokio-timer]
version = "0.2"
optional=true

